version: 0.2

phases:
  build:
    commands:
      - mkdir /data
      - cd /usr/local/bin/
      - ./solana-snapshot-etl "http://api.mainnet-beta.solana.com/snapshot.tar.bz2" --sqlite-out /data/snapshot.db