version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - apt update && apt upgrade
      - apt install curl -y
      - curl -sL https://deb.nodesource.com/setup_16.x | bash -
      - apt -y install nodejs
      - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
  pre_build:
    on-failure: ABORT
    commands:
      - PNPM_HOME="${WORKDIR}/pnpm"
      - mkdir /data
  build:
    commands:
      - "SLOT=$(curl -sfLS http://api.mainnet-beta.solana.com -X POST -H \"Content-Type: application/json\" -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"getEpochInfo\"}' | jq .result.absoluteSlot)"
      - pnpm install --frozen-lockfile
      - pnpm run cli -- filters --json-output filters.json
      - /usr/local/bin/solana-snapshot-etl "http://api.mainnet-beta.solana.com/snapshot.tar.bz2" --sqlite-out /data/snapshot.db
      - pnpm run cli parse --sqlite /data/snapshot.db --output /data/snapshot.csv --slot "$SLOT"
  env:
    POSTGRES_URL: ssm:/marinade/solana-snapshot-manager/db/prod
