version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - apt update && apt upgrade
      - apt install curl -y && apt install nodejs npm -y
      - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
  pre_build:
    on-failure: ABORT
    commands:
      - WORKDIR=$(pwd)
      - PNPM_HOME="${WORKDIR}/pnpm"
  build:
    commands:
      - pnpm install
      - mkdir /data
      - cd /usr/local/bin/
      - ./solana-snapshot-etl "http://api.mainnet-beta.solana.com/snapshot.tar.bz2" --sqlite-out /data/snapshot.db
      - pnpm run cli parse --sqlite /data/snapshot.db --output /data/snapshot.csv