version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
      - pnpm config set store-dir pnpm/store
  pre_build:
    on-failure: ABORT
    commands:
      - WORKDIR=$(pwd)
      - PNPM_HOME="${WORKDIR}/pnpm"
  build:
    commands:
      - mkdir /data
      - cd /usr/local/bin/
      - ./solana-snapshot-etl "http://api.mainnet-beta.solana.com/snapshot.tar.bz2" --sqlite-out /data/snapshot.db