version: '3'

services:

  fetcher:
    image: 400405091548.dkr.ecr.eu-central-1.amazonaws.com/marinade.finance/snapshot-finder:2799b92
    volumes:
      - data:/data

  parser:
    image: 400405091548.dkr.ecr.eu-central-1.amazonaws.com/marinade.finance/snapshot-etl:c555c31
    volumes:
      - data:/data
    depends_on:
      fetcher:
        condition: service_completed_successfully

volumes:
  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/data'
